// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Practica3_PlaylistAPI.DbContexts;

#nullable disable

namespace Practica3_PlaylistAPI.Migrations
{
    [DbContext(typeof(CantanteInfoContext))]
    [Migration("20221107105037_CantanteDBInitialMigration")]
    partial class CantanteDBInitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("Practica3_PlaylistAPI.Entities.Cancion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantanteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estreno")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CantanteId");

                    b.ToTable("Canciones");
                });

            modelBuilder.Entity("Practica3_PlaylistAPI.Entities.Cantante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cantantes");
                });

            modelBuilder.Entity("Practica3_PlaylistAPI.Entities.Cancion", b =>
                {
                    b.HasOne("Practica3_PlaylistAPI.Entities.Cantante", "Cantante")
                        .WithMany("Canciones")
                        .HasForeignKey("CantanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cantante");
                });

            modelBuilder.Entity("Practica3_PlaylistAPI.Entities.Cantante", b =>
                {
                    b.Navigation("Canciones");
                });
#pragma warning restore 612, 618
        }
    }
}
